### ISSUE TITLE
plugin conflict -- sidebar_hide does not work

### ISSUE THREAD

**Issue by DarkSideGeek** [koppen/redmine-pepper-theme#33]
The sidebar_hide plugin does not function on the Pepper theme. The sidebar hides properly, but in other themes, the main content slides over to fill the void. 

The sidebar plugin is well received, and there has been talk of folding it into the main code base. So if that happens, this won't be a mere cross-plugin conflict!

**Comment by cou2jpn** [comment]
Please try this change. Although unable to provide adequate support...
https://github.com/cou2jpn/redmine-pepper-theme/commit/aafee7bb8c952c883592ee5e9a4aa85ba056add6

**Comment by DarkSideGeek** [comment]
Better late than never? I can confirm the @cou2jpn patch works with Pepper+sidebar_hide. The supplied diff was relative to an older version of Pepper's application.css; the newer has compressed all the whitespace, but the code is fundamentally unchanged.

Thanks!

**Comment by koppen** [comment]
"Better late than never" - that should be my open source motto! ;)

I have merged @cou2jpn's changes in 9c3b23e3f26d6972590a49580ce0be695adcbc47, so closing this now.

**Comment by koppen** [comment]
Thanks for your contributions and verifications :)
